### ISSUE TITLE
Vue파일 내 TabView 사용 시 에러

### ISSUE THREAD

**Issue by uz2ni** [uz2ni/warigari-app#1]
app.js에 Vue 컴포넌트 삽입하여 render시키는데 아래와 같은 에러 발생.

`StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.vuetest/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: Cannot read property 'nativeView' of undefined
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: Cannot read property 'nativeView' of undefined
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	... 11 more`

**Comment by uz2ni** [comment]
[요청] nativescript community 에 에러 확인 질문 요청
[답변] 여기를 살펴보라고 하심
https://github.com/nativescript-community/ui-material-components/blob/master/demo-vue/app/main.ts

내 프로젝트랑 임포트 형식?이 달라서 모르겠다..

**Comment by uz2ni** [comment]
[해결]
근본적인 원인은 nativescript 문법을 잘못 입력한 것이였다.
탭뷰 내 property를 적용해두었는데 사용하지 않고있어서 에러가 났다.
지우니까 정상 동작 하였다.

`<TabView :selectedIndex="selectedIndex">` ->  `<TabView>`
